* Emacs config

My emacs config is based on Org files that are parsed and transformed into emacs lisp.

** Files

- =init.el= does nothing except parsing and converting org files
- =config/*.org= are the config files themselves. Config is embed in org source code blocks
    - [[./config/common.org][config/common.org]]: generic configuration
    - [[./config/packages.org][config/packages.org]]: list and install wanted packages
    - [[./config/modes.org][config/modes.org]]: configuration for modes that require one
    - [[./config/keybindings.org][config/keybindings.org]]: the keyboard mapping
    - there are special org files in the config directory named after the machine names I use. It provides specific config for each machine.

** Install and run

*** Clone this repository

=git clone https://github.com/pierre-lecocq/emacs.d .emacs.d=

*** Build lisp code

A Makefile is provided in order to do some operations:

- =make= builds everything
- =make clean= removes the /config/*.el/ files that were previously generated
- =make restart= removes /config/*.el/ files and the whole /el-get/ directory

Therefore:

- to start from the begining, type =make=
- after any config/*.org modification, type =make clean && make=
- to restart the deployment from the begining (the hard way), type =make reset && make=

** Emacs for developers tutorial

In order to know how to setup Emacs from the begining and build your development environment, you really should refer to the [[https://github.com/pierre-lecocq/emacs4developers][emacs4developers tutorial]].
