* My emacs config

My emacs config is based on Org files that are parsed and transformed into emacs lisp.

** Files

- =init.el= does nothing except parsing and converting org files
- =config/*.org= are the config files themselves. Config is embed in org source code blocks
- there is a spacial org file in the config directory named after the local machine name. It provides specific config for each machine.

** Install and run

A Makefile is provided in order to do some operations:

- =make= builds everything
- =make clean= removes the /config/*.el/ files that were previously generated
- =make restart= removes /config/*.el/ files and the whole /el-get/ directory

Therefore:

- to start from the begining, type =make=
- after any config/*.org modification, type =make clean && make=
- to restart the deployment from the begining (the hard way), type =make reset && make=

** Credits

Some parts of this configuration is inspired by great people such as Bastien Guerry, Dimitri Fontaine, Magnars, Sacha Chua, Nic Ferrier, Thomas K Nilsson, ... and many more.
