* Emacs config

My emacs config is based on Org files that are parsed and transformed into emacs lisp.

Literate programming make it more readable!

** Files

- =init.el= does nothing except parsing and converting org files
- =config/org/*.org= are the config files themselves. Config is embed in org source code blocks
    - [[./config/org/01-packages.org][config/org/01-packages.org]]: list and install wanted packages
    - [[./config/org/02-common.org][config/org/02-common.org]]: generic configuration
    - [[./config/org/03-autoinsert.org][config/org/03 autoinsert.org]]: autoinsert settings
    - [[./config/org/04-orgmode.org][config/org/04-orgmode.org]]: orgmode specific configuration
    - [[./config/org/09-keybindings.org][config/org/09-keybindings.org]]: keybindings
    - there are special org files in the config directory named after the machine names I use (=config/org/99-*.org=). It provides specific config for each machine.

** Install and run

*** Clone this repository

=git clone https://github.com/pierre-lecocq/emacs.d .emacs.d=

*** Build lisp code

A Makefile is provided in order to do some operations:

- =make= builds everything
- =make org-mode= builds org-mode from sources
- =make clean= removes the /config/elisp/*.el/ files that were previously generated
- =make reset= removes /config/elisp/*.el/ files and /el-get/, /elpa/, /org-mode/ directories

Therefore:

- to start from the begining, type =make org-mode && make=
- after any config/org/*.org modification, type =make clean && make=
- to restart the deployment from the begining (the hard way), type =make reset && make org-mode && make=

*** Possible troubles

- On MacOSX, the =make= command may fail. Instead of that, just launch Emacs.app, and it will handle all for you (compilation and packages installation).

** Emacs for developers tutorial

In order to know how to setup Emacs from the begining and build your development environment, you really should refer to the [[https://github.com/pierre-lecocq/emacs4developers][emacs4developers tutorial]].

** Gnus configuration example

Gnus is an amazing email reader within Emacs. To see a configuration example, please refer to [[http://qsdfgh.com/articles/gnus-configuration-example.html][qsdfgh.com/gnus-configuration-example.html]].
